development:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://#{ENV["lando_sdohplace_development_solr_conn_host"] || "127.0.0.1"}:#{ENV["lando_sdohplace_development_solr_conn_port"] || 8983}/solr/sdohplace-core-dev" %>
test: &test
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://#{ENV["lando_sdohplace_test_solr_conn_host"] || "127.0.0.1"}:#{ENV['SOLR_TEST_PORT'] || ENV["lando_sdohplace_test_solr_conn_port"] || 8984}/solr/sdohplace-core-test" %>
production:
  adapter: solr
  url: <%= ENV['SOLR_URL'] %>